"""AlphaForge: general-purpose data/feature management for financial ML."""

from .data.context import DataContext
from .data.fred_source import FREDDataSource
from .data.panel import PanelFrame
from .data.pit_source import PITDataSource
from .data.public_web import (
    ANPFuelPricesDataSource,
    B3HistoricalQuotesDataSource,
    BCBSGSDataSource,
    BEADataSource,
    BLSDataSource,
    CFTCCoTSource,
    CFTCDisaggregatedCoTSource,
    CFTCWeeklySwapsSource,
    CMEProductSlateSource,
    DestatisGenesisDataSource,
    DTCCPPDSource,
    ECBSDMXDataSource,
    ECWeeklyOilBulletinDataSource,
    EIADataSource,
    EurexRefdataContractsSource,
    EurexStatsDailySource,
    EurostatDataSource,
    EzoicAdRevenueDailySource,
    FRBTermStructureBenchmarkSource,
    IBGESidraDataSource,
    LCHCDSClearDailySource,
    MOFJGBYieldCurveSource,
    PhiladelphiaSPFMeanLevelSource,
    default_public_web_sources,
)
from .data.query import Query
from .data.schema import TableSchema
from .data.short_rates import (
    ShortRateDataset,
    build_duan_weekly_dataset,
    build_kim_orphanides_dataset,
    build_macro_finance_dataset,
    build_policy_rule_dataset,
)
from .data.universe import EntityMetadata, Universe
from .features.frame import Artifact, FeatureFrame
from .features.market import LagReturnsTemplate, RollingVolatilityTemplate
from .features.ops import join_feature_frames, materialize
from .features.realization import FeatureRealization, FitState
from .features.template import FeatureTemplate, ParamSpec, SliceSpec
from .futures import (
    FirstRateBarsAdapter,
    FirstRateBarsConfig,
    FirstRateFuturesAdapter,
    FirstRateFuturesArtifacts,
    FirstRateFuturesConfig,
    FirstRateFuturesLoader,
    FirstRateFuturesRootMetadata,
    build_first_rate_bars_context,
    build_first_rate_futures_context,
    load_first_rate_futures_metadata,
)
from .pit.accessor import PITAccessor
from .pit.contract import PIT_CONTRACT_VERSION, PITContractVersion, get_pit_contract_version
from .pit.exceptions import (
    PITCausalityError,
    PITContractError,
    PITEngineError,
    PITError,
    PITExperimentalFeatureError,
    PITUnsupportedOperationError,
    PITValidationError,
    PITValidationWarning,
)
from .pit.guards import ReleaseLagPolicy, effective_asof, pit_leakage_report
from .pit.models import (
    PITExpressionGraphResult,
    PITExpressionGraphSpec,
    PITExpressionNode,
    PITFoldSpec,
    PITSequenceMode,
    PITTapeSpec,
    ReleaseRecord,
    ReleaseSelectionPolicy,
    SnapshotSeriesSpec,
    coerce_expression_graph_spec,
    coerce_pit_tape_spec,
    coerce_snapshot_series_spec,
)
from .pit.pipelines import (
    PITPipelineResult,
    PITPipelineSpec,
    PITPipelineStep,
    coerce_pipeline_spec,
)
from .pit.queries import (
    RefRevisionQuery,
    RefSnapshotQuery,
    coerce_ref_revision_query,
    coerce_ref_snapshot_query,
)
from .pit.ref_entity import make_ref_entity_id, parse_ref_entity_id
from .pit.tasks import (
    build_snapshot_tape,
    first_vintage_snapshot,
    forward_fill_with_staleness,
    iter_purged_kfold_folds,
    iter_walk_forward_folds,
    latest_vintage_snapshot,
    qoq,
    revision_deltas,
    revision_event_stream,
    revision_events,
    revision_stability,
    revision_volatility,
    snapshot_at_horizon,
    yoy,
)
from .pit.transforms import PITTransformResult, PITTransformSpec
from .pit.validation import PITValidationReport, validate_pit_observations
from .registry import EntityEntry, EntityRegistry
from .store.cache import MaterializationPolicy
from .store.duckdb_parquet import DuckDBParquetStore
from .time.align import AlignedPanel, AlignSpec, AvailabilityState, align_panel
from .time.calendar import TradingCalendar
from .time.grids import EventGrid, Grid, NativeGrid, SessionGrid
from .time.missingness import MissingnessReason, classify_missingness
from .time.ref_period import (
    ObsDateAnchor,
    RefFreq,
    RefPeriod,
    coerce_ref_period,
    normalize_obs_date_anchor,
    normalize_ref_freq,
)
from .time.release_rules import (
    CalendarDay,
    CustomRule,
    FixedLagMonths,
    NthBusinessDay,
    NthWeekday,
    QuarterlyRelease,
    ReleaseRule,
    WeeklyRelease,
)

__all__ = [
    "DataContext",
    "FREDDataSource",
    "Query",
    "TableSchema",
    "PanelFrame",
    "PITDataSource",
    "ShortRateDataset",
    "FirstRateBarsAdapter",
    "FirstRateBarsConfig",
    "FirstRateFuturesAdapter",
    "FirstRateFuturesArtifacts",
    "FirstRateFuturesConfig",
    "FirstRateFuturesLoader",
    "FirstRateFuturesRootMetadata",
    "build_first_rate_bars_context",
    "build_first_rate_futures_context",
    "load_first_rate_futures_metadata",
    "BLSDataSource",
    "BEADataSource",
    "CFTCCoTSource",
    "CFTCDisaggregatedCoTSource",
    "EIADataSource",
    "EurostatDataSource",
    "ECBSDMXDataSource",
    "DestatisGenesisDataSource",
    "ECWeeklyOilBulletinDataSource",
    "IBGESidraDataSource",
    "BCBSGSDataSource",
    "ANPFuelPricesDataSource",
    "B3HistoricalQuotesDataSource",
    "DTCCPPDSource",
    "CMEProductSlateSource",
    "CFTCWeeklySwapsSource",
    "EurexStatsDailySource",
    "EurexRefdataContractsSource",
    "LCHCDSClearDailySource",
    "EzoicAdRevenueDailySource",
    "FRBTermStructureBenchmarkSource",
    "MOFJGBYieldCurveSource",
    "PhiladelphiaSPFMeanLevelSource",
    "default_public_web_sources",
    "build_kim_orphanides_dataset",
    "build_policy_rule_dataset",
    "build_duan_weekly_dataset",
    "build_macro_finance_dataset",
    "Universe",
    "EntityMetadata",
    "TradingCalendar",
    "Grid",
    "SessionGrid",
    "NativeGrid",
    "EventGrid",
    "AlignSpec",
    "AlignedPanel",
    "AvailabilityState",
    "align_panel",
    "RefFreq",
    "RefPeriod",
    "ObsDateAnchor",
    "coerce_ref_period",
    "normalize_ref_freq",
    "normalize_obs_date_anchor",
    "ReleaseRule",
    "NthBusinessDay",
    "NthWeekday",
    "CalendarDay",
    "FixedLagMonths",
    "QuarterlyRelease",
    "WeeklyRelease",
    "CustomRule",
    "MissingnessReason",
    "classify_missingness",
    "FeatureFrame",
    "Artifact",
    "LagReturnsTemplate",
    "ParamSpec",
    "RollingVolatilityTemplate",
    "SliceSpec",
    "FeatureTemplate",
    "FeatureRealization",
    "FitState",
    "MaterializationPolicy",
    "materialize",
    "DuckDBParquetStore",
    "join_feature_frames",
    "PITAccessor",
    "PITError",
    "PITContractError",
    "PITValidationError",
    "PITUnsupportedOperationError",
    "PITExperimentalFeatureError",
    "PITCausalityError",
    "PITEngineError",
    "PITValidationWarning",
    "PITTransformSpec",
    "PITTransformResult",
    "PITPipelineStep",
    "PITPipelineSpec",
    "PITPipelineResult",
    "coerce_pipeline_spec",
    "RefSnapshotQuery",
    "RefRevisionQuery",
    "coerce_ref_snapshot_query",
    "coerce_ref_revision_query",
    "PITExpressionNode",
    "PITExpressionGraphSpec",
    "PITExpressionGraphResult",
    "coerce_expression_graph_spec",
    "PITFoldSpec",
    "PITTapeSpec",
    "PITSequenceMode",
    "coerce_pit_tape_spec",
    "ReleaseSelectionPolicy",
    "ReleaseRecord",
    "SnapshotSeriesSpec",
    "coerce_snapshot_series_spec",
    "PITContractVersion",
    "PIT_CONTRACT_VERSION",
    "get_pit_contract_version",
    "PITValidationReport",
    "validate_pit_observations",
    "ReleaseLagPolicy",
    "effective_asof",
    "pit_leakage_report",
    "first_vintage_snapshot",
    "latest_vintage_snapshot",
    "snapshot_at_horizon",
    "revision_deltas",
    "revision_events",
    "revision_event_stream",
    "revision_stability",
    "revision_volatility",
    "forward_fill_with_staleness",
    "yoy",
    "qoq",
    "iter_walk_forward_folds",
    "iter_purged_kfold_folds",
    "build_snapshot_tape",
    "make_ref_entity_id",
    "parse_ref_entity_id",
    "EntityEntry",
    "EntityRegistry",
]
